routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

//  Route::get('/', function () {
//    return view('/Home');
// });

Route::middleware('auth_token')->group(function () {
    Route::get('/', 'HomeController@getIndex');
    Route::get('home', 'HomeController@getIndex');
    Route::get('addEvent', 'addEvent@getIndex');

    Route::resource('article', 'ManagerArticleController');

    Route::get('articles', 'ManagerArticleController@show');

});
Route::get('login', ['as' => 'login', 'uses' => 'LoginController@getLogin']);
Route::post('login', 'LoginController@postLogin');

resources/views/Home.blade.php
@extends('master')
@section('main')

<div><h3>Chào mừng các bạn đến với Trang Quản Lý TStudents</h3></div>
@stop

resources/views/addArticle.blade.php
@extends('master')
@section('main')
<div class="panel panel-primary" style="margin-top:50px">
    <form action="{!! route('article.store') !!}" method="POST" enctype="multipart/form-data">
        <div class="panel-body">
            <legend><h2>Tạo Bài Viết Mới </h2></legend>
            Tiêu Đề Bài Đăng:
            <textarea class="form-control" rows="3" name="Title" ></textarea><br/>
            @if($errors->has('Title'))
            <p style="color: red">{{$errors->first('Title')}}</p>
            @endif
            Mô Tả Ngắn Gọn Bài Đăng: <br/>`
            <textarea class="form-control" rows="4" name = "Description" id="Description"></textarea><br/>
            @if($errors->has('Description'))
            <p style="color: red">{{$errors->first('Description')}}</p>
            @endif
            Hình ảnh tiêu đề: <input type="file" id='image' name="image" onchange="readURL(this);"> <br />
            <img id="blah" height="150px" src="{{asset('image/upload_photo.png')}}" alt="your image" /><br /> <br/>
            @if($errors->has('image'))
            <p style="color: red">{{$errors->first('image')}}</p>
            @endif
            Nội Dung Bài Đăng: <br/>
            <textarea name="content" id="content" >This is content ...</textarea>
            @if($errors->has('content'))
            <p style="color: red">{{$errors->first('content')}}</p>
            @endif
            <script>
                CKEDITOR.replace( 'content',{ filebrowserBrowseUrl: '/browser/browse.php'
                                ,filebrowserUploadUrl: '/uploader/upload.php'});
                var data = CKEDITOR.instances.text.getData();
            </script>
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            {{-- @csrf
            <input type = "hidden" name="_token" value="{{ csrf_field() }}" > --}}
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">Đăng bài</button>
        </div>
    </form>
</div>
@stop

resources/views/addEvent.blade.php
@extends('master')
@section('main')
<div class="panel panel-primary" style="margin-top:50px">
    <div class="panel-body" >
        <legend><h2>Tạo Sự Kiện Mới</h2></legend>
        <form action="../api/XLDL/addActivity.php" method="POST" enctype="multipart/form-data">
            Tên Sự Kiện:
            <input class="form-control" name="nameAct" ><br/>

            Thời Gian Bắt Đầu:
            <div class="form-group col-12">
                <div class="input-group date form_datetime col-md-12" data-date="01-06-2019 10:00" data-date-format="dd MM yyyy - HH:ii p" data-link-field="dtp_input1">
                    <input class="form-control" name="timeStar" size="16" type="text" value="" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                </div>
                <input type="hidden" id="dtp_input1" value="" /><br/>
            </div>
            Thời Gian Kết Thúc:
            <div class="form-group col-12">
                <div class="input-group date form_datetime col-md-12" data-date="" data-date-format="dd MM yyyy - HH:ii p" data-link-field="dtp_input1">
                    <input class="form-control" size="16" name="timeEnd" type="text" value="" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                </div>
                <input type="hidden" id="dtp_input1" value="" /><br/>
            </div>
            Thời Gian Bắt Đầu Điểm Danh:
            <div class="form-group col-12">
                <div class="input-group date form_datetime col-md-12" data-date="" data-date-format="dd MM yyyy - HH:ii p" data-link-field="dtp_input1">
                    <input class="form-control" size="16" name="DeadlineStar"  type="text" value="" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                </div>
                <input type="hidden" id="dtp_input1" value="" /><br/>
            </div>
            Thời Gian Kết Thúc Điểm Danh:
            <div class="form-group col-12">
                <div class="input-group date form_datetime col-md-12" data-date="" data-date-format="dd MM yyyy - HH:ii p" data-link-field="dtp_input1">
                    <input class="form-control" name="DeadlineEnd" size="16" type="text" value="" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                </div>
                <input type="hidden" id="dtp_input1" value="" /><br/>
            </div>
            Địa điểm:  <textarea class="form-control" name="Acplace" ></textarea><br/>
            Nội dung: <textarea class="form-control" rows='5' name="AcContent" ></textarea><br/>
            Hình ảnh Hoạt động<input type="file" id='image' name="image" onchange="readURL(this);"> <br />
                <img id="blah" height="150px" width="150px" src="http://placehold.it/150" alt="your image" /><br /> <br/>
            Điểm hoạt động:  <input type="number" class="form-control" name="ACPoint" ><br/>
            Số Lượng:  <input type="number" class="form-control" name="AcNum" ><br/>
            <button type="submit" class="btn btn-primary">Tạo hoạt động</button>
        </form>
    </div>
</div>
<script type="text/javascript" src="{{asset('bootstrap-datetimepicker-master/sample in bootstrap v3/jquery/jquery-1.8.3.min.js')}}" charset="UTF-8"></script>

<script type="text/javascript" src="{{asset('bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.min.js')}}"></script>

<script type="text/javascript" src="{{asset('bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js')}}" charset="UTF-8"></script>

<script type="text/javascript" src="{{asset('bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.fr.js')}}" charset="UTF-8"></script>

<link href="{{asset('bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" media="screen">

<script type="text/javascript">
    $('.form_datetime').datetimepicker({
        //language:  'fr',
        format: 'yyyy-mm-dd hh:ii',
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1
    });
</script>
@endsection

resources/views/editArticle.blade.php
@extends('master')
@section('main')
<div class="panel panel-primary" style="margin-top:50px">
            <form method="POST" action="{{ route('article.update',$article->id)}}"  enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="panel-body">
                    <legend><h2 > Sửa Bài Viết </h2></legend>
                    Tiêu Đề Bài Đăng:
                <textarea class="form-control" rows="3" name="Title" >{{ $article->Title }}</textarea><br/>
                    @if($errors->has('Title'))
                    <p style="color: red">{{ $errors->first('Title') }}</p>
                    @endif
                    Mô Tả Ngắn Gọn Bài Đăng: <br/>
                    <textarea class="form-control" rows="4" name = "Description" id="Description">{{ $article->Description }}</textarea><br/>
                    @if($errors->has('Description'))
                    <p style="color: red">{{$errors->first('Description')}}</p>
                    @endif
                    Hình ảnh tiêu đề: <input type="file" id='image' name="image" onchange="readURL(this);"> <br />
                    <img id="blah" height="150px" src="{{asset('image/'.$article->ImageUrl)}}" alt="your image" /><br /> <br/>
                    @if($errors->has('image'))
                    <p style="color: red">{{ $errors->first('image') }}</p>
                    @endif
                    Nội Dung Bài Đăng: <br/>
                    <textarea name="content" id="content" >{{$article->Content}}</textarea>
                    @if($errors->has('content'))
                    <p style="color: red">{{$errors->first('content')}}</p>
                    @endif
                    <script>
                        CKEDITOR.replace( 'content',{ filebrowserBrowseUrl: '/browser/browse.php'
                                        ,filebrowserUploadUrl: '/uploader/upload.php'});
                        var data = CKEDITOR.instances.text.getData();
                    </script>
                </div>
                <div class="panel-footer">
                    <button type="submit" class="btn btn-primary">Sửa bài viết</button>
                </div>
        </form>
</div>
@stop

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel=icon href="{{asset('image/Logo.png')}}" sizes="57x57" type="image/png">
    <title>Đăng nhập Administartor Tstudents</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <!-- <link href="{{asset('css/metisMenu.min.css')}}" rel="stylesheet"> -->

    <!-- Custom CSS -->
    <link href="{{asset('css/login.css')}}" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
</head>

<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-form-title" style="background-image: asset('image/login.jpg')">
                    <span class="login100-form-title-1">
                        Đăng Nhập
                    </span>
                </div>

                <form class="login100-form validate-form" role="form" method="POST" action="{{url('login')}}">
                    @if($errors->has('user'))
                    <p style="color: red">{{$errors->first('user')}}</p>
                    @endif
                    <div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
                        <span class="label-input100">Email</span>
                        <input class="input100" type="text" placeholder="Nhập email" id="user" name="user" type="text" autofocus>
                    </div>
                    @if($errors->has('password'))
                    <p style="color: red">{{$errors->first('password')}}</p>
                    @endif
                    <div class="wrap-input100 validate-input m-b-18" data-validate="Password is required">
                        <span class="label-input100">Mật khẩu</span>
                        <input class="input100" placeholder="Nhập mật khẩu" id="password" name="password" type="password" value="">
                    </div>
                    @if($errors->has('errorLogin'))
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <p>{{$errors->first('errorLogin')}}</p>
                    </div>
                    @endif
                    <div class="remember">
                        <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember">
                        <label class="label-checkbox100" for="ckb1">
                            Nhớ mật khẩu
                        </label>
                    </div>
                    @csrf
                    <div class="container-login100-form-btn">
                        <button type="submit" class=" login100-form-btn">Đăng nhập</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="{{asset('js/jquery.min.js')}}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{asset('js/bootstrap.min.js')}}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{asset('js/metisMenu.min.js')}}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{asset('js/startmin.js')}}"></script>
</body>

</html>

resources/views/managerarticles.blade.php
@extends('master')
<!-- @section('main') -->
<!-- @if (session()->has('success'))
<script type="text/javascript">
alert({
    {
        session() - > get('success')
    }
});
</script>
@endif -->
<div class="panel-body">
    <div class="table-responsive">
        <legend>
            <h1>Xem tất cả bài viết</h1>
        </legend>
        <!-- <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>ManagerID</th>
                    <th>Image</th>
                    <th>Content</th>
                    <th>TimeUpLoad</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach($article as $articles)
                    <tr>
                        <td>{{$articles->id}}</td>
                        <td>{{$articles->Title}}</td>
                        <td>{{$articles->Description}}</td>
                        <td>{{$articles->ManagerID}}</td>
                        <td>
                            @if($articles->ImageUrl !=null)
                                <img width="100px" height="100px" src="{{asset('image/'.$articles->ImageUrl)}}" class="img-thumbnail" alt="Cinque Terre">
                            @else
                                <img width="100px" height="100px" src="{{asset('image/default_image.png')}}" class="img-thumbnail" alt="Cinque Terre">
                            @endif
                        </td>
                        <td>{{$articles->Content}}</td>
                        <td>{{$articles->TimeUpLoad}}</td>
                        <td>
                            <div class="row" style="padding-right:15%">

                                <a  href="{{ route('article.edit',$articles->id) }}"><button type="Button"  class="btn btn-primary col-xs-11">Sửa</button></a>
                                <form method="POST" action="{{ route('article.destroy',$articles->id)}}">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <div class="form-group">
                                        <input type="submit"  onclick="return confirm('Bạn có chắc chắn xóa?')" class="col-xs-11 btn btn-danger delete-article" value="Xóa">
                                    </div>
                                </form>
                                {{-- {{ Form::open(array('route'=>array('article.destroy',$articles->id),'method'=>'DELETE')) }}
                                    <input type="submit"  onclick="return confirm('Bạn có chắc chắn xóa?')" class="col-xs-11 btn btn-danger delete-article" value="Xóa">
                                    {{ csrf_field() }}
                                {{ Form::close() }} --}}
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{$article->links()}} -->
    </div>
    <!-- /.table-responsive -->
</div>
<!-- @stop -->

resources/views/master.blade.php
<?php use Illuminate\Support\Facades\Cache;
$user = Cache::get('auth_user');
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="">

    <title>Admin Tstudents TDMU</title>
    @yield('title')
    <link rel=icon href="{{asset('image/Logo.png')}}" sizes="57x57" type="image/png">
    <!-- Bootstrap Core CSS -->
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <!-- <link href="{{asset('css/metisMenu.min.css')}}" rel="stylesheet"> -->

    <!-- Timeline CSS -->
    <!-- <link href="{{asset('css/timeline.css')}}" rel="stylesheet"> -->

    <!-- Custom CSS -->


    <!-- Morris Charts CSS -->
    <!-- <link href="{{asset('morris.css')}}" rel="stylesheet"> -->

    <!-- Custom Fonts -->
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.0.13/css/all.css'>
    <link rel="stylesheet" href="{{asset('css/main.css')}}">

    <script src="{{asset('ckeditor/ckeditor.js')}}"></script>

    <script src="{{asset('js/bootstrap.min.js')}}"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="{{asset('js/fileInput.js')}}"></script>
</head>

<body>

    <div class="page-wrapper chiller-theme toggled">
        <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <div class="sidebar-brand">
                    <a href="#">T Students Administrator</a>
                    <div id="close-sidebar">
                        <i class="fas fa-times"></i>
                    </div>
                </div>
                <div class="sidebar-header">
                    <div class="user-pic">
                        <img class="img-responsive img-rounded"
                            src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                            alt="User picture">
                    </div>
                    <div class="user-info">
                        <span class="user-name">{{ $user}}
                        </span>
                        <span class="user-role">Quản trị viên</span>
                        <span class="user-status">
                            <i class="fa fa-circle"></i>
                            <span>Online</span>
                        </span>
                    </div>
                </div>
                <!-- sidebar-header  -->
                <div class="sidebar-search">
                    <div>
                        <div class="input-group">
                            <input type="text" class="form-control search-menu" placeholder="Tìm kiếm...">
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- sidebar-search  -->
                <div class="sidebar-menu">
                    <ul>
                        <li class="header-menu">
                            <span>Tổng quan</span>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fa fa-tachometer-alt"></i>
                                <span>Trạng thái</span>
                                <!-- <span class="badge badge-pill badge-warning">New</span> -->
                            </a>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="{!! route('article.create') !!}">
                                <i class="fa fa-edit"></i>
                                <span>Viết bài</span>
                                <!-- <span class="badge badge-pill badge-danger">3</span> -->
                            </a>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="{!! route('article.index') !!}">
                                <i class="far fa-newspaper"></i>
                                <span>Xem bài viết</span>
                            </a>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fa fa-chart-line"></i>
                                <span>Hoạt động</span>
                            </a>
                        </li>
                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="fa fa-check"></i>
                                <span>Điểm danh</span>
                            </a>
                        </li>
                        <li class="header-menu">
                            <span>Quản lý</span>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-user-graduate"></i>
                                <span>Sinh viên</span>
                                <!-- <span class="badge badge-pill badge-primary">Beta</span> -->
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-file"></i>
                                <span>Tệp tin</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- sidebar-menu  -->
            </div>
            <!-- sidebar-content  -->
            <div class="sidebar-footer">
                <!-- <a href="#">
                    <i class="fa fa-bell"></i>
                    <span class="badge badge-pill badge-warning notification">3</span>
                </a>
                <a href="#">
                    <i class="fa fa-envelope"></i>
                    <span class="badge badge-pill badge-success notification">7</span>
                </a> -->
                <a href="#">
                    <i class="fa fa-cog"></i>
                    <!-- <span class="badge-sonar"></span> -->
                </a>
                <a href="{!! route('login') !!}">
                    <i class="fa fa-power-off"></i>
                </a>
            </div>
        </nav>
        <!-- sidebar-wrapper  -->
        <main class="page-content">
            @yield('main')
        </main>
        <!-- page-content" -->
    </div>
    <!-- jQuery -->
    <script src="{{asset('js/jquery.min.js')}}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    <script src="{{asset('js/main.js')}}"></script>
    <script src="{{asset('js/feather.min.js')}}"></script>
    <script>
    feather.replace()
    </script>
</body>

</html>